### ISSUE TITLE
Add Netlify CI

### ISSUE THREAD

**Issue by Siilwyn** [Siilwyn/get-ci-env#12]
https://www.netlify.com/docs/continuous-deployment/#build-environment-variables

Does it have target branch data? #3

**Comment by jbmoelker** [comment]
property | env variable
--- | ---
`service` | ?
`branch` | `BRANCH`
`commit` | `COMMIT_REF`
`repo` | `REPOSITORY_URL`
`pr` | `REVIEW_ID`

**Comment by Siilwyn** [comment]
`service` = `NETLIFY`
The `REPOSITORY_URL` is an odd one: `https://x-access-token:v1.49c8bfc86a17dc3e14b1a5ddb22ce750e8353624@github.com/voorhoede/echo-env`. Could request Netlify to expose the owner and project name or parse the URL. Wonder what the URL looks like for GitLab, and need to handle the possibility of a project with no linked git.

**Comment by Siilwyn** [comment]
Got the idea to do some housekeeping here too after our call. =)

Closing this for now since Netlify misses the target branch environment variable.
