### ISSUE TITLE
Investigate additional CI services to support

### ISSUE THREAD

**Issue by Siilwyn** [Siilwyn/get-ci-env#2]
Investigate which CI services provide all needed environment variables and add support:
- [x] Jenkins
- [x] TeamCity
- [x] Codeship
- [x] GitLab CI
- [x] AppVeyor

**Comment by jbmoelker** [comment]
There's a [looooong list of CI services](https://stackify.com/top-continuous-integration-tools/). Maybe only add the ones you need, once you need them?

**Comment by Siilwyn** [comment]
Hmm good point, I'll need to look into which CI services provide all needed environment variables. It's pretty easy to add more.

**Comment by Siilwyn** [comment]
Sadly all services are missing one or more variables, going to open a GitLab CI issue for now to track upstream issue.

**Jenkins**
*GIT_URL contains url to git repository, needs URL parsing.*
branch: GIT_BRANCH
commit: GIT_COMMIT
repoOwner: GIT_URL
repoName: GIT_URL
prNumber: **missing**
detection: JENKINS_URL

**TeamCity**
branch: **missing**
commit: BUILD_VCS_NUMBER
repoOwner: **missing**
repoName: TEAMCITY_PROJECT_NAME
prNumber: **missing**
detection: TEAMCITY_VERSION

**Codeship**
*CI_NAME contains 'codeship'.*
branch: CI_BRANCH
commit: CI_COMMIT_ID
repoOwner: CI_REPO_NAME[0]
repoName: CI_REPO_NAME[1]
prNumber: **missing**
detection: CI_NAME

**GitLab CI**
branch: CI_COMMIT_REF_NAME
commit: CI_COMMIT_SHA
repoOwner: CI_PROJECT_PATH[0]
repoName: CI_PROJECT_NAME
prNumber: **missing**
detection: GITLAB_CI

**AppVeyor**
*Branch is only available for non-pr builds as `APPVEYOR_REPO_BRANCH`.*
branch: **missing**
commit: APPVEYOR_REPO_COMMIT
repoOwner: APPVEYOR_REPO_NAME[0]
repoName: APPVEYOR_REPO_NAME[1]
prNumber: APPVEYOR_PULL_REQUEST_NUMBER
detection: APPVEYOR
