### ISSUE TITLE
Add GitLab CI

### ISSUE THREAD

**Issue by Siilwyn** [Siilwyn/get-ci-env#7]
Only missing `prNumber` known as merge request at GitLab: https://gitlab.com/gitlab-org/gitlab-ce/issues/15280

branch: `CI_COMMIT_REF_NAME`
commit: `CI_COMMIT_SHA`
repoOwner: `CI_PROJECT_PATH`
repoName: `CI_PROJECT_NAME`
prNumber: `CI_MERGE_REQUEST_IID`
detection: `GITLAB_CI`

Blocked: https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/5792

**Comment by glensc** [comment]
gitlab has merge-request, not pull-request, do you plan aliasing `mrNumber` to `prNumber`?

**Comment by glensc** [comment]
for repoOwner, full group path must be used not just first component:

- https://gitlab.com/gitlab-org/examples/mvn-example

repo owner=gitlab-org/examples

for repo name, is it full path, or just last component?\

repo name=mvn-example or gitlab-org/examples/mvn-example ?

**Comment by Siilwyn** [comment]
@glensc thanks for the feedback, I'll take a look at these once I get around implementing this. As for the naming an alias might be possible but not sure if it's needed. :+1:

**Comment by Siilwyn** [comment]
So it looks like `prNumber` will be `CI_MR_IID` which will also be used for PR detection since it's unset in other cases.

Finally looked into this more, @glensc think it would make most sense to do:
- repoOwner: gitlab-org
- repoName: examples/mvn-example

**Comment by glensc** [comment]
no, the owner may be different for each group, so:

- repoOwner: gitlab-org/examples
- repoName: mvn-example

**Comment by Siilwyn** [comment]
I understand the owner can be different but I don't understand why it's more logical to put the group under the owner instead of the repo name. :thinking:

**Comment by glensc** [comment]
and I don't understand why you want to put part of group name to repo name.

my suggestion matches how gitlab api uses them:
- https://docs.gitlab.com/ce/api/projects.html#list-all-projects

```json
    "path": "diaspora-client",
    "path_with_namespace": "diaspora/diaspora-client",
```

really, up to you, as neither of us has actual usecase for this. i don't even plan using this project.

**Comment by Siilwyn** [comment]
Ah matching the API makes a lot of sense, again thanks for the input!
